const dummydata = [
    { 
        id:1,
        title:"Learn React in 2023",
        channelName:"Code Academy",
        thumbnail:"https://i.ytimg.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
        profilePic:"https://i.ytimg.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
        category:"Education",
        like:"500K",
        views:"1M",
    },

     { 
        id:2,
        title:"Swimming Tutorial for Beginners",
        channelName:"Vlad and Niki",
        thumbnail:"https://i.ytimg.com/vi/ZtuyYwxueZQ/maxresdefault.jpg",
        profilePic:"https://yt3.googleusercontent.com/il7dQx5fz3qs2ykOvWQVhtjT-_grY_oPmXlah13q694r_5zUS_7M33pBuUC34Cq0VearBaT1NOE=s900-c-k-c0x00ffffff-no-rj",
        category:"kids shows",
        like:"500K",
        views:"1M",
    },
     { 
        id:3,
        title:"Behance song",
        channelName:"Music Lover",
        thumbnail:"https://mir-s3-cdn-cf.behance.net/project_modules/fs/3f2259119268281.609a2dc4ece4d.png",
        profilePic:"https://mir-s3-cdn-cf.behance.net/project_modules/fs/3f2259119268281.609a2dc4ece4d.png",
        category:"Music",
        like:"500K",
        views:"1M",
    },
     { 
        id:4,
        title:"Rootha Rabb",
        channelName:"Vishnu Dileep",
        thumbnail:"https://cdn.dribbble.com/userupload/39933762/file/original-68ef62cd1e35f3365aa378e2c4014fe6.png?resize=1200x973&vertical=center",
        profilePic:"https://cdn.dribbble.com/userupload/39933762/file/original-68ef62cd1e35f3365aa378e2c4014fe6.png?resize=1200x973&vertical=center",
        category:"Music",
        like:"500K",
        views:"1M",
    },
     { 
        id:5,
        title:"Lorem ipsum",
        channelName:"BBC News",
        thumbnail:"https://img.freepik.com/free-psd/youtube-news-channel-cover_23-2148972532.jpg?semt=ais_hybrid&w=740&q=80",
        profilePic:"https://yt3.googleusercontent.com/v4JamQ9B-PUiJHjmZQs9UwTaoLQW8vijJMMpV5QvA2wHQ6iwWM8Q1s6O4jgTl0dtDigVWAi7SA=s900-c-k-c0x00ffffff-no-rj",
        category:"News",
        like:"500K",
        views:"1M",
    },
     { 
        id:6,
        title:"New President 2023",
        channelName:"BBC News",
        thumbnail:"https://piktochart.com/wp-content/uploads/2022/12/large-18-600x338.jpg",
        profilePic:"https://yt3.googleusercontent.com/v4JamQ9B-PUiJHjmZQs9UwTaoLQW8vijJMMpV5QvA2wHQ6iwWM8Q1s6O4jgTl0dtDigVWAi7SA=s900-c-k-c0x00ffffff-no-rj",
        category:"News",
        like:"500K",
        views:"1M",
    },
     { 
        id:7,
        title:"Live news",
        channelName:"BBC News",
        thumbnail:"https://img.freepik.com/free-psd/live-streaming-3d-render-icon_47987-9046.jpg?w=360",
        profilePic:"https://yt3.googleusercontent.com/v4JamQ9B-PUiJHjmZQs9UwTaoLQW8vijJMMpV5QvA2wHQ6iwWM8Q1s6O4jgTl0dtDigVWAi7SA=s900-c-k-c0x00ffffff-no-rj",
        category:"Live",
        like:"500K",
        views:"1M",
    },
     { 
        id:8,
        title:"Car Games",
        channelName:"PX-5",
        thumbnail:"https://www.shutterstock.com/image-vector/power-play-dynamic-gaming-controller-260nw-2321548437.jpg",
        profilePic:"https://static.vecteezy.com/system/resources/thumbnails/002/144/780/small/gaming-banner-for-games-with-glitch-effect-neon-light-on-text-illustration-design-free-vector.jpg",
        category:"Gaming",
        like:"500K",
        views:"1M",
    },
     { 
        id:9,
        title:"Alladin movie ",
        channelName:"Movie123",
        thumbnail:"https://lumiere-a.akamaihd.net/v1/images/alladin_600x450_moviespg_mobile_7_d097b99b.jpeg?region=0,0,600,450",
        profilePic:"https://static.vecteezy.com/system/resources/thumbnails/002/144/780/small/gaming-banner-for-games-with-glitch-effect-neon-light-on-text-illustration-design-free-vector.jpg",
        category:"Movies",
        like:"500K",
        views:"1M",
    },
     { 
        id:10,
        title:"Season 3",
        channelName:"Coke Studio",
        thumbnail:"https://m.media-amazon.com/images/S/pv-target-images/9ed79902cec009cb879269fea595589a6474a39541bef3ef04ded81f55a72b66.jpg",
        profilePic:"https://m.media-amazon.com/images/M/MV5BOWI4YjZhZDYtYWIyMi00Y2M4LTkyNmUtNmE1ODdiYmQxNDQwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        category:"coke studio",
        like:"500K",
        views:"1M",
    },


   

]
export default dummydata;